//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EagleEye.rc
//
#define IDM_GETPHOTOS                   100
#define IDM_VIEW_LIST                   101
#define IDM_VIEW_ICON                   102
#define IDM_VIEW_DETAILS                103
#define IDS_APP_TITLE                   103
#define IDM_VIEW_TILES                  104
#define IDS_STRING_FULLSCREEN           104
#define IDM_OPTIONS                     105
#define IDS_STRING_WINDOW               105
#define IDM_ABOUT                       106
#define IDS_STRING_BILINEAR             106
#define IDS_STRING_NEAREST              107
#define IDS_STRING_PIXEL                108
#define IDS_STRING_UNKNOWN              109
#define IDS_STRING_4INDEXED             110
#define IDS_STRING_8INDEXED             111
#define IDS_STRING_16RGB                112
#define IDS_STRING_24RGB                113
#define IDS_STRING_32RGB                114
#define IDS_STRING_32ARGB               115
#define IDS_STRING_48RGB                116
#define IDS_STRING_64ARGB               117
#define IDS_STRING_FILEINFO             118
#define IDS_STRING_ZOOMED               119
#define IDS_STRING_FILES                120
#define IDS_STRING_SIZE                 121
#define IDS_STRING_MB                   122
#define IDS_STRING_TAG                  123
#define IDS_STRING_VALUE                124
#define IDS_STRING_EXIFNOTAVAILABLE     125
#define IDS_STRING_CANONMN              126
#define IDS_STRING_BPP                  127
#define IDS_STRING_PIXELS               128
#define IDS_STRING_MPIXELS              129
#define IDS_STRING_BYTES                130
#define IDR_MENU2                       143
#define IDS_GET_PHOTOS                  143
#define IDS_VIEW_LIST                   144
#define IDS_VIEW_ICON                   145
#define IDS_VIEW_DETAILS                146
#define IDD_GET_PHOTOS                  147
#define IDS_VIEW_TILES                  147
#define IDS_OPTIONS                     148
#define IDS_ABOUT                       149
#define IDI_EAGLEEYE                    150
#define IDI_ICON_JPG                    151
#define IDI_ICON_TIFF                   152
#define IDI_ICON_BMP                    153
#define IDI_ICON_PNG                    154
#define IDI_ICON_GIF                    155
#define IDI_ICON_EXIF                   156
#define IDI_ICON_EMF                    157
#define IDI_ICON_WMF                    158
#define IDI_ICON_ICO                    159
#define IDD_ABOUT                       160
#define IDR_ABOUT_SPLASH                175
#define IDI_GET_PHOTOS                  180
#define IDI_VIEW_LIST                   181
#define IDI_VIEW_ICON                   182
#define IDI_VIEW_DETAIL                 183
#define IDI_VIEW_TILE                   184
#define IDI_OPTIONS                     185
#define IDI_ABOUT                       186
#define IDD_THUMBNAILS                  231
#define IDD_PROPEXIF                    232
#define IDD_OPTION                      233
#define IDD_PROPFILE                    234
#define IDR_MENU1                       300
#define ID_STATUSBAR                    500
#define ID_TOOLBAR                      501
#define IDS_EXT1                        700
#define IDS_EXT2                        701
#define IDS_EXT3                        702
#define IDS_EXT4                        703
#define IDS_EXT5                        704
#define IDS_EXT6                        705
#define IDS_EXT7                        706
#define IDS_EXT8                        707
#define IDS_EXT9                        708
#define IDS_EXT10                       709
#define IDS_EXT11                       710
#define IDS_EXT12                       711
#define IDS_EXT13                       712
#define IDS_EXT14                       713
#define IDS_EXT15                       714
#define IDC_EAGLEEYE                    1001
#define IDC_LIST1                       1052
#define IDC_TREE1                       1055
#define IDC_COMBO1                      1066
#define IDC_SLIDER1                     1067
#define IDC_BORDER_COLOR_BUTTON         1068
#define IDC_BORDER_COLOR                1069
#define IDC_SPLITTER_SIZE_TEXT          1070
#define IDC_BACKTH_COLOR_BUTTON         1072
#define IDC_BACKTH_COLOR                1073
#define IDC_PROP_FILENAME               1074
#define IDC_PROP_DIRECTORY              1075
#define IDC_PROP_PATH                   1076
#define IDC_PROP_FORMAT                 1077
#define IDC_PROP_SIZE                   1078
#define IDC_PROP_COLORS                 1079
#define IDC_PROP_UNCOLORS               1080
#define IDC_PROP_DISKSIZE               1081
#define IDC_PROP_MEMSIZE                1082
#define IDC_PROP_DATE                   1083
#define IDC_PROP_DIRINDEX               1084
#define IDC_SEL_FOLDER                  1087
#define IDC_CLEAN_FOLDER                1088
#define IDC_CUR_CACHE_DIR               1089
#define IDC_FULLSCREEN                  1090
#define IDC_BILINEAR                    1091
#define IDC_CHECK_FOLDER_CONTEXT        1092
#define IDC_CHECK_EXT1                  1093
#define IDC_CHECK_EXT2                  1094
#define IDC_IMAGE_CONTROL               1094
#define IDC_CHECK_EXT3                  1095
#define IDC_EDIT_SUBFOLDER              1095
#define IDC_CHECK_EXT4                  1096
#define IDC_EDIT_LOCATION               1096
#define IDC_CHECK_EXT5                  1097
#define IDC_BUTTON_BROWSE               1097
#define IDC_CHECK_EXT6                  1098
#define IDC_CHECK_DELETE_AFTER          1098
#define IDC_CHECK_EXT7                  1099
#define IDC_RADIO_KEEP_FILE_NAMES       1099
#define IDC_CHECK_EXT8                  1100
#define IDC_RADIO_DATA_FILE_NAMES       1100
#define IDC_CHECK_EXT9                  1101
#define IDC_CHECK_GO_TO_DIRECTORY       1101
#define IDC_PROGRESS_PROGRESS           1102
#define IDC_CHECK_EXT10                 1102
#define IDC_BUTTON_GET_DATE             1103
#define IDC_CHECK_EXT11                 1103
#define IDC_CHECK_EXT12                 1104
#define IDC_CHECK_EXT13                 1105
#define IDC_CHECK_EXT14                 1106
#define IDC_CHECK_EXT15                 1107
#define ID_FIT                          32773
#define ID_FULL                         32774
#define ID_DELETEFILE                   32777
#define ID_FULLSCREEN                   32781
#define ID_BILINEARMODE                 32783
#define ID_RCOMPONENT                   32787
#define ID_BCOMPONENT                   32788
#define ID_GCOMPONENT                   32789
#define ID_ROTATE90                     32791
#define ID_HORIZONTALFLIP               32794
#define ID_VERTICALFLIP                 32795
#define ID_SAVEFILE                     32797
#define ID_OPENFILE                     32799
#define ID_SAVEFILEAS                   32801
#define ID_PROPERTYEXIF                 32803
#define ID_THUMBNAILS                   32805
#define ID_GRAYSCALE                    32808
#define ID_ACOMPONENT                   32810
#define ID_MENU_OPTIONS                 32813
#define ID_MENU_PROPFILE                32814
#define ID_WALLPAPER_CENTERED           32817
#define ID_WALLPAPER_TILED              32818
#define ID_WALLPAPER_STRETCH            32819
#define ID_MENU_EXIT                    32824
#define ID_MENU_ABOUT                   32825
#define ID_MENU_GETPICTURE              32826
#define ID_VIEWMODE_LIST                32829
#define ID_VIEWMODE_ICON                32830
#define ID_VIEWMODE_DETAILS             32831
#define ID_VIEWMODE_TILES               32832
#define ID_FILE_COPY                    32833
#define ID_FILE_COPYTO                  32834
#define ID_EDIT_COPY                    32836
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
